name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Backend Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend/*"
          target: "/home/ubuntu/Helix_Cloud_bootcamp/backend"

      - name: Deploy Application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            cd /home/ubuntu/Helix_Cloud_bootcamp/backend

            # Create virtual environment if it doesn't exist
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

            source venv/bin/activate

            pip install --upgrade pip

            pip install -r requirements.txt

            # Stop existing application if running
            PID=$(pgrep -f "python3 main.py")
            if [ -n "$PID" ]; then
                echo "Stopping process $PID"
                kill "$PID"
                sleep 3
            fi

            

        
             # Start new version
             nohup python3 main.py > app.log 2>&1 &
            

            
