name: Deploy to AWS

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Start SSH agent and add private key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Add EC2 to known hosts
      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Deploy to EC2
      - name: Deploy application
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          ssh $USER@$HOST << 'EOF'
            echo "Connected to server"

            cd /home/Helix_Cloud_bootcamp/backend || exit

            echo "Pulling latest code..."
            git pull origin main

            echo "Activating virtual environment..."
            source ../venv/bin/activate

            echo "Installing dependencies..."
            pip install -r requirements.txt

            echo "Running migrations..."
            python manage.py migrate --noinput

            echo "Collecting static files..."
            python manage.py collectstatic --noinput

            echo "Deployment successful!"
          EOF
