name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            echo "========== Updating Project =========="

            cd /home/ubuntu/Helix_Cloud_bootcamp

            git pull origin main

            echo "========== Installing Node.js =========="

            # Install Node.js if it is not installed
            if ! command -v node >/dev/null 2>&1; then

              echo "Node.js not found. Installing..."

              curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -

              sudo apt-get install -y nodejs

            else

              echo "Node.js already installed"

            fi

            echo "Node Version:"
            node -v

            echo "NPM Version:"
            npm -v

            echo "========== Installing Frontend Dependencies =========="

            cd frontend

            npm install

            echo "========== Restarting Frontend =========="

            sudo systemctl restart helix-frontend

            echo "========== Frontend Status =========="

            sudo systemctl status helix-frontend --no-pager
